FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app
RUN go install github.com/pressly/goose/v3/cmd/goose@latest

FROM alpine:latest

RUN apk add --no-cache libc6-compat

WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /go/bin/goose /usr/local/bin/goose
COPY --from=builder /app/migrations ./migrations

CMD ["sh", "-c", "goose -dir /root/migrations postgres \"$DATABASE_URL\" up && ./main"]