FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app
RUN CGO_ENABLED=0 GOOS=linux go build -o migrator ./cmd/migrator

FROM alpine:latest

RUN apk add --no-cache libc6-compat

WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/migrator .
COPY --from=builder /app/migrations ./migrations

CMD ["./migrator"] # поравить, чтобы запускалось не каждый раз при запуске контейнера
CMD ["./main"]