FROM golang:latest AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/app
RUN CGO_ENABLED=0 GOOS=linux go build -o migrator ./cmd/migrator

FROM alpine:latest

RUN apk add --no-cache libc6-compat

WORKDIR /root/
COPY --from=builder /app/main .
COPY --from=builder /app/migrator .
COPY --from=builder /app/migrations ./migrations

RUN echo '#!/bin/sh' > entrypoint.sh && \
    echo '' >> entrypoint.sh && \
    echo 'if [ ! -f /root/migrations_done ]; then' >> entrypoint.sh && \
    echo '  ./migrator' >> entrypoint.sh && \
    echo '  touch /root/migrations_done' >> entrypoint.sh && \
    echo 'fi' >> entrypoint.sh && \
    echo '' >> entrypoint.sh && \
    echo 'exec ./main "$@"' >> entrypoint.sh && \
    chmod +x entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]